from . import res_config_settings
from . import whatsapp_api
from . import whatsapp_wizard
from . import whatsapp_message_log
from . import whatsapp_template
from . import whatsapp_campaign
from . import whatsapp_campaign_queue
from . import whatsapp_campaign_step
from . import whatsapp_account
from . import res_partner
from . import account_move
